// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Aestus.API.Data;

public partial class AestusDBContext : DbContext
{
    public AestusDBContext(DbContextOptions<AestusDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Setting> Settings { get; set; }

    public virtual DbSet<SettingVersion> SettingVersions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Setting>(entity =>
        {
            entity.HasKey(e => e.SettingId).HasName("PK__Settings__54372AFD629E7F40");

            entity.HasIndex(e => e.SettingName, "UQ__Settings__BCA5D463F533DA14").IsUnique();

            entity.Property(e => e.SettingId).HasColumnName("SettingID");
            entity.Property(e => e.SettingName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<SettingVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("PK__SettingV__16C6402FD2D2CFD7");

            entity.HasIndex(e => new { e.SettingId, e.StartDate }, "UQ_SettingVersion").IsUnique();

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.SettingId).HasColumnName("SettingID");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Value).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Setting).WithMany(p => p.SettingVersions)
                .HasForeignKey(d => d.SettingId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__SettingVe__Setti__3B75D760");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}