// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Aestus.API.Data;

public partial class Setting
{
    public int SettingId { get; set; }

    public string SettingName { get; set; }

    public virtual ICollection<SettingVersion> SettingVersions { get; set; } = new List<SettingVersion>();
}